version: '3.8'

services:
  chat-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: socket-chat-container
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
